# Generated by Django 4.2 on 2026-03-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('standard', models.IntegerField()),
                ('place', models.CharField(max_length=50)),
            ],
        ),
    ]
